# Generated by Django 5.1.4 on 2026-06-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('handled', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='meeting',
            name='bot_name',
            field=models.CharField(blank=True, help_text='Name the bot shows as in the call', max_length=80),
        ),
        migrations.AddField(
            model_name='meeting',
            name='deployed_now',
            field=models.BooleanField(default=False, help_text='Bot was deployed immediately'),
        ),
    ]
