# Generated by Django 5.1.4 on 2026-06-14 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0002_contactmessage_meeting_bot_name_meeting_deployed_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='media_url',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='s3_url',
            field=models.TextField(blank=True),
        ),
    ]
