# Generated by Django 5.1.4 on 2026-06-14 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0003_alter_recording_media_url_alter_recording_s3_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='bot_status_detail',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='meeting_url',
            field=models.URLField(max_length=1000),
        ),
    ]
