# Generated by Django 5.1.4 on 2026-07-25 12:11

import django.db.models.deletion
import django.utils.timezone
import meetings.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0004_alter_meeting_bot_status_detail_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeetingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='MeetingShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=meetings.models._share_token, max_length=64, unique=True)),
                ('visibility', models.CharField(choices=[('link', 'Anyone with the link'), ('restricted', 'Only specific people')], default='link', max_length=12)),
                ('allowed_emails', models.JSONField(blank=True, default=list)),
                ('include_transcript', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='meeting',
            name='status_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='emaillog',
            name='kind',
            field=models.CharField(choices=[('welcome', 'Welcome'), ('login_alert', 'Login alert'), ('meeting_notes', 'Meeting notes'), ('password_reset', 'Password reset'), ('share_invite', 'Share invite'), ('share_access', 'Share access link')], default='meeting_notes', max_length=20),
        ),
        migrations.AlterField(
            model_name='meeting',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('joining', 'Joining'), ('waiting', 'In waiting room'), ('recording', 'Recording'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=16),
        ),
        migrations.AddIndex(
            model_name='meeting',
            index=models.Index(fields=['recall_bot_id'], name='meetings_me_recall__81723a_idx'),
        ),
        migrations.AddField(
            model_name='meetingevent',
            name='meeting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='meetings.meeting'),
        ),
        migrations.AddField(
            model_name='meetingshare',
            name='meeting',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='share', to='meetings.meeting'),
        ),
        migrations.AddIndex(
            model_name='meetingevent',
            index=models.Index(fields=['meeting', '-created_at'], name='meetings_me_meeting_7254a8_idx'),
        ),
    ]
