# Generated by Django 5.1.4 on 2026-07-27 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0005_meetingevent_meetingshare_meeting_status_changed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='voice_agent_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
