# Generated by Django 5.1.4 on 2026-07-27 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetings', '0006_meeting_voice_agent_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='voice_gender',
            field=models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=8),
        ),
    ]
